# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    export GITHUB_TOKEN='$(GH_SECRET)'
    gh auth login
    gh auth status
  displayName: 'Authenticate GitHub CLI Credentials'
    
- bash: |
    echo "=============================================================================="
    echo "Pushing the Following Files:"
    ls -la /home/vsts/work/1/s
    echo "=============================================================================="
    echo "Most Recent Commits:"
    git log --pretty=oneline
    echo "=============================================================================="
  displayName: 'Print Git Logs'

- bash: |
    mkdir -p /home/vsts/.ssh
    ls -al /home/vsts
    echo '$(rsa_private_key)' > /home/vsts/.ssh/id_rsa
    echo "SSH Keys:"
    ls /home/vsts/.ssh 
    git config --global --add url."benjawilson@github.com:".insteadOf "https://github.com/"
    git remote set-url origin https://github.com/benjawilson/PartsUnlimited
    git remote -v
    git push --all
  displayName: 'Sync Repositiry with GitHub'

  


