# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    export GITHUB_TOKEN='$(GH_SECRET)'
    gh auth login
    gh auth status
  displayName: 'Authenticate GitHub Credentials'
