# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    export GITHUB_TOKEN='$(GH_SECRET)'
    gh auth login
    gh auth status
  displayName: 'Authenticate GitHub CLI Credentials'
    
- bash: |
    echo "=============================================================================="
    echo "Pushing the Following Files:"
    ls -la /home/vsts/work/1/s
    echo "=============================================================================="
    echo "Most Recent Commits:"
    git log --pretty=oneline
    echo "=============================================================================="
  displayName: 'Print Git Logs'

- bash: |   
    export AZURE_URL=https://dKomplexDev@dev.azure.com/dKomplexDev/Parts%20Unlimited/_git/Parts%20Unlimited
    export GH_URL=https://'$(GH_USERNAME)':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@github.com/benjawilson/PartsUnlimitedAz/
    sed -e "s|$AZURE_URL|$GH_URL|" .git/config > .git/config2
    mv .git/config2 .git/config
    git config --global user.name "Ben"
    cat .git/config
    git push --mirror https://github.com/benjawilson/PartsUnlimitedAz

#- bash: |
#    git remote set-url origin https://github.com/benjawilson/PartsUnlimited
#    git config --global --add url."benjawilson@github.com:".insteadOf "https://github.com/"
#    export SSH_ASKPASS='$(RSA_KEY)'
#    git push --all
#  displayName: 'Git Push'


#- bash: |
#   mkdir -p /home/vsts/.ssh
#    ls -al /home/vsts
#    echo '$(RSA_KEY)' > /home/vsts/.ssh/id_rsa
#    chmod 600 /home/vsts/.ssh/id_rsa
#    ls /home/vsts/.ssh 
#    git config --global --add url."benjawilson@github.com:".insteadOf "https://github.com/"
#    git remote set-url origin https://github.com/benjawilson/PartsUnlimited
#    git remote -v
#    git push --all
#  displayName: 'Sync Repositiry with GitHub'

  


